#lang racket/base
(require racket/list "../cuda/driver.rkt" "../cuda/gpu.rkt" "../field.rkt")
(gpu-init!)
(define (rows F n lim)
  (for/list ([_ (in-range n)])
    (for/list ([_ (in-range n)])
      (make-cyc F (for/list ([_ (in-range (field-degree F))]) (- (random (* 2 lim)) lim))))))
(printf "~a ~a ~a ~a\n" "field" "n" "poll_ms" "block_ms")
(for ([nn (in-list '(8 24))])
  (define F (make-field nn))
  (for ([n (in-list '(512 1024))])
    (define A (zmat-of-integers F (rows F n (if (= nn 8) 512 128))))
    (void (gpu-matmul A A #:audit? #f))
    (define (timeit mode)
      (parameterize ([current-gpu-wait mode])
        (define t (current-inexact-milliseconds))
        (for ([_ (in-range 3)]) (void (gpu-matmul A A #:audit? #f)))
        (/ (- (current-inexact-milliseconds) t) 3)))
    (printf "Q(z~a) ~a ~a ~a\n" nn n (round (timeit 'poll)) (round (timeit 'block)))))
(gpu-shutdown!)
